const moviesActionTypes = {
  // Movie List
  FETCH_MOVIES_START: "FETCH_MOVIES_START",
  FETCH_MOVIES_SUCCESS: "FETCH_MOVIES_SUCCESS",
  FETCH_MOVIES_FAILURE: "FETCH_MOVIES_START",
  SET_PAGE_NUMBER: "SET_PAGE_NUMBER",
  CLEAR_MOVIES_LIST: "CLEAR_MOVIES_LIST",
  // Movie
  FETCH_MOVIE_START: "FETCH_MOVIE_START",
  FETCH_MOVIE_SUCCESS: "FETCH_MOVIE_SUCCESS",
  FETCH_MOVIE_FAILURE: "FETCH_MOVIE_FAILURE",
  LOADING_MOVIE: "LOADING_MOVIE",
  SEARCH_MOVIE: "SEARCH_MOVIE",
  CHANGE_SEARCH_QUERY: "CHANGE_SEARCH_QUERY"
};

export default moviesActionTypes;
